### ISSUE TITLE
Provide link to episode page hosted by Buzzsprout

### ISSUE THREAD

**Issue by patrickfweston** [buzzsprout/buzzsprout-api#5]
Hey there! Thanks for creating such an easy API to work with. I wanted to provide folks with a link to the episode on Buzzsprout. I found that I could construct a URL to that, and I thought I'd document it for other folks. It'd be great if this could be a property returned by the API, too.

```
$episode->url = sprintf("https://www.buzzsprout.com/%s/%s", $podcast_id, $episode->id);
```
This is a PHP snippet where `$podcast_id` is your podcast's ID as determined by Buzzsprout, and the `$episode->id` is in the API response.

Thanks!

**Comment by johnloringpollard** [comment]
Nice code! We provide the `audio_url` in the API response which is almost the same thing as the episode's public URL page on Buzzsprout. The only difference is the format `.mp3` for the audio file and `.html` (or no format listed which defaults to HTML) for the public page. You could also remove the format to have the public page URL. I don't think we will return that URL in the API response right now since it is so close to the audio_url already returned from the API. But if this becomes a bigger issue we will readdress then!

**Comment by patrickfweston** [comment]
Ah, good call — I might do that instead since it contains a portion of the title instead of a more cryptic URL. Thank you!
