### ISSUE TITLE
How to GET a single episode

### ISSUE THREAD

**Issue by jaymakes11** [buzzsprout/buzzsprout-api#9]
The only supported GET endpoint I see mentioned here is `episodes.json` (for getting _all_ episodes). 

I assume it's possible to get a single episode? If so, how?

**Comment by johnloringpollard** [comment]
No it is not currently, but let me look into adding that!

**Comment by yet-another-dev** [comment]
Ah, yikes! That's pretty crucial (and basic) functionality! Surprised to see it's missing. Yes, it'd be great to get this added.

**Comment by tomrossi7** [comment]
Definitely would be nice to add to the API, but in the meantime, you can actually just hit the public page for the episode with a .json extension. So `http://www.buzzsprout.com/podcast_id/episode_id.json`

**Comment by yet-another-dev** [comment]
Ahh, nice. That's help, probably sufficient for my current needs.

Displaying the episode ID somewhere in the Buzzsprout dashboard would be really helpful (especially with a "copy" button). I know it's just the last segment of the URL, but for non-technical folks, the UX would be a lot better if it was explicitly displayed.

**Comment by yet-another-dev** [comment]
Also, from my testing, it seems the `podcast_id` isn't necessary (just some type of placeholder), e.g. 

```
http://www.buzzsprout.com/_/episode_id.json
```

Any reason not to do this? Are `episode_id`s guaranteed to be unique across podcasts?

**Comment by johnloringpollard** [comment]
We also use the podcast_id to scope whatever endpoint you're using. For instance episodes/create needs the podcast_id. This helps keep all endpoints following the same pattern. The only time you dont need it is for podcasts/index of course.

**Comment by yet-another-dev** [comment]
> With that said, the SHOW episode endpoint has been added and the docs will be updated soon.

Nice! That was _fast_!

> Displaying the episode ID somewhere in the Buzzsprout dashboard would be really helpful (especially with a "copy" button). I know it's just the last segment of the URL, but for non-technical folks, the UX would be a lot better if it was explicitly displayed.

Any chance we could get something like this added? I can share more on our particular use case (publishing flow) if that'd be useful.

**Comment by johnloringpollard** [comment]
You are right the episode ID shows up the in the URL many times from admin. Thats probably the best way to get it if you dont want to use the API. The intent of the API is to work the API and not with sections of the admin UI. So if you want an episode ID, you would pull a list of episodes from the API instead of looking into your admin. I hope that makes sense!

**Comment by yet-another-dev** [comment]
> You are right the episode ID shows up the in the URL many times from admin. Thats probably the best way to get it if you dont want to use the API. The intent of the API is to work the API and not with sections of the admin UI. So if you want an episode ID, you would pull a list of episodes from the API instead of looking into your admin. I hope that makes sense!

I still think there's significant value in clearly labeling and displaying the episode ID for each episode in the UI. Consider a publishing workflow where a non-technical client is posting a new episode in the Buzzsprout UI and then adding that episode into a CMS. Yes, having the new episodes added to the CMS programmatically is ideal, but in some cases it's not always feasible or even preferable (in which case they need to be able to easily get the episode ID in order to make the link between the CMS and Buzzsprout).

**Comment by duynguyen145-dev** [comment]
Hi @johnloringpollard  @tomrossi7 
Also, from my investigating, it seems the **podcast_id, api_token** aren't necessary while call via API, e.g.

http://www.buzzsprout.com/api/episode_id.json
https://www.buzzsprout.com/api/5145481.json
Any reason not to do this? Please advice!

**Comment by tomrossi7** [comment]
You should use the API URL. The publicly available json URL is not documented and may not be supported in the future.
